database:
  host: 'localhost'
  port: '3306'
  DBname: 'kitpvp_database'
  username: 'root'
  password: ''
lobby-spawn:
  world: 'world'
  x: 0
  y: 0
  z: 0
  pitch: 0
  yaw: 0
arena-spawn:
  world: 'world'
  x: 0
  y: 0
  z: 0
  pitch: 0
  yaw: 0
arenasign:
  line1: '&6-- ARENA --'
  line2: '&7-> Click to join <-'
  line3: '&6-----'
  line4: ''
  key: 'arenasign'
kits:
  pvp:
    inventory:
      gui-display: 'PvP'
      gui-material: 'DIAMOND_SWORD'
      name: 'pvp'
    items:
      - DIAMOND_SWORD
      - APPLE;10
    armor:
      helmet: 'DIAMOND_HELMET'
      chestplate: 'GOLD_CHESTPLATE'
      leggings: 'IRON_LEGGINGS'
      boots: 'IRON_BOOTS'
